spring:
 application:
  name: api-gateway

 cloud:
  loadbalancer:
   enabled: true

  gateway:
   server:
    webflux:
     routes:
      - id: msv-categorias
        uri: lb://msv-categorias
        predicates:
         - Path=/api/categorias/**
        filters:
         - StripPrefix=2

      - id: msv-proveedores
        uri: lb://msv-proveedores
        predicates:
         - Path=/api/proveedores/**
        filters:
         - StripPrefix=2

      - id: msv-productos
        uri: lb://msv-productos
        predicates:
         - Path=/api/productos/**
        filters:
         - StripPrefix=2

server:
 port: 8090

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka